spring.application.name=elearning-backend


#=============Mysql cfgs================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Elearning_db
spring.datasource.username=root
spring.datasource.password=root


#===========JPA properties===========
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


#===============server port===========
#server.port=4041

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manishsharma62876@gmail.com
spring.mail.password=Mani@1+1

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
